/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface AppRoot {

    }
  }

  interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-root': JSXElements.AppRootAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRootAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface RxDemo {

    }
  }

  interface HTMLRxDemoElement extends StencilComponents.RxDemo, HTMLStencilElement {}

  var HTMLRxDemoElement: {
    prototype: HTMLRxDemoElement;
    new (): HTMLRxDemoElement;
  };
  interface HTMLElementTagNameMap {
    'rx-demo': HTMLRxDemoElement;
  }
  interface ElementTagNameMap {
    'rx-demo': HTMLRxDemoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'rx-demo': JSXElements.RxDemoAttributes;
    }
  }
  namespace JSXElements {
    export interface RxDemoAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
